### ISSUE TITLE
MerossIot refactor breaks current compatibility

### ISSUE THREAD

**Issue by albertogeniola** [vincenzosuraci/hassio_meross_sensor_switch#7]
Hi @vincenzosuraci ,
thanks for your great component. I would like to inform you that the future version of the library will break some interfaces that your component currently uses. So, I'd suggest you to have a look at the brach named [0.3.X.X on MerossIot repository](https://github.com/albertogeniola/MerossIot/tree/0.3.X.X). 
Before releasing such version I'd like to get some feedback from you about its working status and its usability.

If I may, I'd suggest you to create a dedicated branch which relies on the new version of the library so that people can still use the previous one while we are working on the new versions.

**Comment by gianky69** [comment]
I’ll be a beta tester 😉

**Comment by arcangelweb** [comment]
Waiting to perform tests.

Thanks for your job

**Comment by vincenzosuraci** [comment]
@albertogeniola I'm getting this error:

```
Traceback (most recent call last):
  File "c:\users\vincenzo\homeassistant\lib\site-packages\homeassistant\setup.py", line 151, in _async_setup_component
    hass, processed_config)
  File "C:\Users\Vincenzo\AppData\Roaming\.homeassistant\custom_components\meross\__init__.py", line 307, in async_setup
    MEROSS_MANAGER: MerossManager(meross_email=username, meross_password=password),
  File "c:\users\vincenzo\homeassistant\lib\site-packages\meross_iot\manager.py", line 36, in __init__
    self._cloud_creds = self._http_client.get_cloud_credentials()
AttributeError: 'MerossHttpClient' object has no attribute 'get_cloud_credentials'
```

VS

**Comment by vincenzosuraci** [comment]
It's a method, not an attribute. Round parenthesis missing. I guess.

VS

**Comment by albertogeniola** [comment]
Hi @vincenzosuraci ,
I have no idea what happened. Probably bad commit/push on the repository. I've just committed the new code to the repository. Should be working now. By the way, I've pulled out the 0.3.0.0 version from PyPi and release this one as 0.3.0.0b0 (beta 0). 

Let me know if that's now working as intended.

Thank you!

**Comment by vincenzosuraci** [comment]
> Hi @vincenzosuraci ,
> I have no idea what happened. Probably bad commit/push on the repository. I've just committed the new code to the repository. Should be working now. By the way, I've pulled out the 0.3.0.0 version from PyPi and release this one as 0.3.0.0b0 (beta 0).
> 
> Let me know if that's now working as intended.
> 
> Thank you!

Now it works

**Comment by vincenzosuraci** [comment]
I delivered branch 3.x.x that uses the new library. I need to perform long lasting tests and I count on volounteers.

VS

**Comment by gianky69** [comment]
Here I am... let's go!
UPDATE: dependencies error...
```
Error loading custom_components.meross. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 263, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/meross/__init__.py", line 7, in <module>
    from meross_iot.cloud.exceptions import CommandTimeoutException, StatusTimeoutException
ModuleNotFoundError: No module named 'meross_iot.cloud'
```
No meross_iot 0.3.0.0b0 on PyPI?

**Comment by vincenzosuraci** [comment]
I do not know why Hassio (HA on RPi) is not downloading it automatically anymore (I have setup it on __init__.py: `REQUIREMENTS = ['meross_iot==0.3.0.0b0']`)...

Instead, if you are in HA, you should be able to do that with the command `py -m pip install meross_iot==0.3.0.0b0`

**Comment by vincenzosuraci** [comment]
@albertogeniola is there a way to disable the log (or to setup the level of the log) in v0.3.0.0b0? Even if I setup the WARNING level, I still see DEBUG an INFO statements. Sorry for the dummy question...

**Comment by vincenzosuraci** [comment]
> No meross_iot 0.3.0.0b0 on PyPI?

I confirm that it is on PyPI.

**Comment by gianky69** [comment]
> 
> 
> I do not know why Hassio (HA on RPi) is not downloading it automatically anymore (I have setup it on **init**.py: `REQUIREMENTS = ['meross_iot==0.3.0.0b0']`)...
> 
> Instead, if you are in HA, you should be able to do that with the command `py -m pip install meross_iot==0.3.0.0b0`

I'm on a remote browser configurator (Hassio HA on RPi)

**Comment by vincenzosuraci** [comment]
@albertogeniola I have an issue: I'm using the Android app version 1.6.0 (updated day). 

If I change the switch status from the Android App, the `event_handler` is not called. Instead if I switch from HA, the App correctly detects the status change.

Since it is the first test I did, I cannot say if before updating to Android app version 1.6.0 the custom-componnet was working. However, I guess this issue is independent from the android App version.

VS

**Comment by vincenzosuraci** [comment]
@albertogeniola I have also this issue: when a `CommandTimeoutException` occurs I would like to intercept it and hanlde the exception. But executing the `except CommandTimeoutException:` piece of code, I get this long error traceback:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\39340\AppData\Roaming\.homeassistant\custom_components\meross\__init__.py", line 135, in update_device_status_by_id
    electricity = meross_device.get_electricity()
  File "c:\users\39340\homeassistant\lib\site-packages\meross_iot\cloud\devices\power_plugs.py", line 135, in get_electricity
    return self._get_electricity()['electricity']
  File "c:\users\39340\homeassistant\lib\site-packages\meross_iot\cloud\devices\power_plugs.py", line 21, in _get_electricity
    return self.execute_command("GET", ELECTRICITY, {})
  File "c:\users\39340\homeassistant\lib\site-packages\meross_iot\cloud\device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "c:\users\39340\homeassistant\lib\site-packages\meross_iot\cloud\client.py", line 300, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting fot the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting fot the ACK: 10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\39340\AppData\Roaming\.homeassistant\custom_components\meross\__init__.py", line 138, in update_device_status_by_id
    except CommandTimeoutException:
TypeError: catching classes that do not inherit from BaseException is not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\39340\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\39340\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\39340\AppData\Roaming\.homeassistant\custom_components\meross\__init__.py", line 87, in thread_main_loop
    thread_update_devices_status(hass, config)
  File "C:\Users\39340\AppData\Roaming\.homeassistant\custom_components\meross\__init__.py", line 162, in thread_update_devices_status
    update_device_status_by_id(hass, meross_device_id)
  File "C:\Users\39340\AppData\Roaming\.homeassistant\custom_components\meross\__init__.py", line 141, in update_device_status_by_id
    except CommandTimeoutException:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by gianky69** [comment]
> 
> 
> I do not know why Hassio (HA on RPi) is not downloading it automatically anymore (I have setup it on **init**.py: `REQUIREMENTS = ['meross_iot==0.3.0.0b0']`)...
> 
> Instead, if you are in HA, you should be able to do that with the command `py -m pip install meross_iot==0.3.0.0b0`

It was my fault, since HA 0.92.x is mandatory to include manifest.json also for custom_components. I was using old method, copying only .py in custom_components/meross.
Remember to update your README.md ;-)

**Comment by vincenzosuraci** [comment]
> > I do not know why Hassio (HA on RPi) is not downloading it automatically anymore (I have setup it on **init**.py: `REQUIREMENTS = ['meross_iot==0.3.0.0b0']`)...
> > Instead, if you are in HA, you should be able to do that with the command `py -m pip install meross_iot==0.3.0.0b0`
> 
> It was my fault, since HA 0.92.x is mandatory to include manifest.json also for custom_components. I was using old method, copying only .py in custom_components/meross.
> Remember to update your README.md ;-)

I updated the README.md. Thanks for the hint!

VS

**Comment by arcangelweb** [comment]
It would be possible to update HassOS

I'm not clear about the procedure

**Comment by gianky69** [comment]
[home-assistant.log.zip](https://github.com/vincenzosuraci/hassio_meross_sensor_switch/files/3128833/home-assistant.log.zip)
There are some WARNING about Meross possibly stuck, the status of entities is not updated, but still working if switch them in HA

**Comment by vincenzosuraci** [comment]
@arcangelweb I'm a bit confused between Hassio, Home Assistant and HassOS. I'm aware of the difference between Hassio (that's for RPi) and Home Assistant (I installed it on a Windows machine). Not sure about HassOS. However, in Hassio, the custom-component must be installed copying the files (*.py and manifest.json) in the folder. Re-starting Hassio ensures that the dependecies are downloaded automatically. In Home Assistant, the dependecies must be installed manually (e.g. using pip). In Hassio the system (i.e. Home Assistant) can be updated directly from the Lovelace UI, while in Home Assistant It must be done manually using command line (hass homeassistant update).

VS

**Comment by vincenzosuraci** [comment]
@gianky69 thanks for the log. With the new version of the meross_iot library there are still some issues to be solved. It is still much less stable than version 2.x.x. I'm trying to improve the quality of the custom component, since I programmed it solving a new issue every time and never had the chance to have the whole problem known from the beginning.

**Comment by gianky69** [comment]
Thanks for your great work!

**Comment by vincenzosuraci** [comment]
Dear all, 
since I developed the version 3.x.x on the base of meross_iot version 3.x.x, I close this issue. But I would like to mention that stability issue are still far to be solved and I need some long lasting tests from all of you.

VS

**Comment by albertogeniola** [comment]
Hi @vincenzosuraci ,
the problem with the StatusTimeoutException and CommandTimeoutException is that you are catching the module and not the class. You can either catch the CommandTimeoutException.CommandTimeoutException (module_name.class_name) or change the import statement so that you import the class and not the module.
